[package]
name = "bitcoin_address_gerenator"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.11.0"
bitcoin = "0.32.5"
bs58 = "0.5.1"
hex = "0.4.3"
ripemd = "0.1.3"
secp256k1 = "0.30.0"
sha2 = "0.10.8"
